"""add_photo_url_and_embedding_to_user

Revision ID: 0c74af5d7572
Revises: 24e6df638ad1
Create Date: 2026-05-08 19:15:31.404560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c74af5d7572'
down_revision: Union[str, Sequence[str], None] = '24e6df638ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PEOPLE', 'embedding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('PEOPLE', 'photo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('USER', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('USER', sa.Column('embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USER', 'embedding')
    op.drop_column('USER', 'photo_url')
    op.alter_column('PEOPLE', 'photo_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('PEOPLE', 'embedding',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
