"""initial schema

Revision ID: 360b64563114
Revises: 
Create Date: 2026-08-24 15:51:06.035533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360b64563114'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('nick_name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_USER_email'), 'USER', ['email'], unique=True)
    op.create_index(op.f('ix_USER_id'), 'USER', ['id'], unique=False)
    op.create_index(op.f('ix_USER_nick_name'), 'USER', ['nick_name'], unique=False)
    op.create_table('PEOPLE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('relation', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PEOPLE_id'), 'PEOPLE', ['id'], unique=False)
    op.create_index(op.f('ix_PEOPLE_name'), 'PEOPLE', ['name'], unique=False)
    op.create_table('PLACE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('visit_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('category_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PLACE_id'), 'PLACE', ['id'], unique=False)
    op.create_index(op.f('ix_PLACE_name'), 'PLACE', ['name'], unique=False)
    op.create_table('SCHEDULE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['PLACE.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SCHEDULE_id'), 'SCHEDULE', ['id'], unique=False)
    op.create_table('ACTIVITY_LOG',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['PLACE.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['SCHEDULE.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_ACTIVITY_LOG_log_id'), 'ACTIVITY_LOG', ['log_id'], unique=False)
    op.create_table('SCHEDULE_PEOPLE',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['PEOPLE.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['SCHEDULE.id'], ),
    sa.PrimaryKeyConstraint('schedule_id', 'people_id')
    )
    op.create_table('LOG_PEOPLE',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['ACTIVITY_LOG.log_id'], ),
    sa.ForeignKeyConstraint(['people_id'], ['PEOPLE.id'], ),
    sa.PrimaryKeyConstraint('log_id', 'people_id')
    )
    op.create_table('PHOTO',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['ACTIVITY_LOG.log_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PHOTO_id'), 'PHOTO', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PHOTO_id'), table_name='PHOTO')
    op.drop_table('PHOTO')
    op.drop_table('LOG_PEOPLE')
    op.drop_table('SCHEDULE_PEOPLE')
    op.drop_index(op.f('ix_ACTIVITY_LOG_log_id'), table_name='ACTIVITY_LOG')
    op.drop_table('ACTIVITY_LOG')
    op.drop_index(op.f('ix_SCHEDULE_id'), table_name='SCHEDULE')
    op.drop_table('SCHEDULE')
    op.drop_index(op.f('ix_PLACE_name'), table_name='PLACE')
    op.drop_index(op.f('ix_PLACE_id'), table_name='PLACE')
    op.drop_table('PLACE')
    op.drop_index(op.f('ix_PEOPLE_name'), table_name='PEOPLE')
    op.drop_index(op.f('ix_PEOPLE_id'), table_name='PEOPLE')
    op.drop_table('PEOPLE')
    op.drop_index(op.f('ix_USER_nick_name'), table_name='USER')
    op.drop_index(op.f('ix_USER_id'), table_name='USER')
    op.drop_index(op.f('ix_USER_email'), table_name='USER')
    op.drop_table('USER')
    # ### end Alembic commands ###
